### ISSUE TITLE
Unable to start a new spreadsheet

### ISSUE THREAD

**Issue by avdata99** [okfn/timemapper#224]
The URL always return 404 internally and shows `That URL doesn't exist` error message

![Selection_368](https://user-images.githubusercontent.com/3237309/131852420-e1d0c620-1db4-4bea-8227-f024cda851ce.png)

Using the URL
https://docs.google.com/spreadsheets/d/1saz7b7WF97xb7EA9XS9ea-q-26owrRteAaNYNgz48Bc

The transformation at
```python
var url = recline.Backend.GDocs.getGDocsApiUrls(e.target.value).spreadsheetAPI;
```
get the URL
https://spreadsheets.google.com/feeds/worksheets/https://docs.google.com/spreadsheets/d/1saz7b7WF97xb7EA9XS9ea-q-26owrRteAaNYNgz48Bc/public/basic?alt=json
(check the two `http` parts, the URL is bad)

We are using a [very old JS library](https://github.com/okfn/recline.backend.gdocs) to build those urls

**Comment by lwinfree** [comment]
As we discussed in slack, I'm posting relevant issue reports here as well to keep track of them. I'm not sure if they are related, or if there is something else going on:
- https://discuss.okfn.org/t/timemapper-down/240/6
- https://github.com/okfn/okfn.github.com/issues/546

**Comment by rufuspollock** [comment]
This has not been maintained for some time. I strongly suspect that google have changed their API for accessing spreadsheets (i have seen this on the net mentioned in the last few years).

**Comment by kcirsresearch** [comment]
This issue is still persisting; has there been any progress on it? Is this the best place to find updates on this issue? Thank you!

**Comment by lwinfree** [comment]
Hi @kcirsresearch! Timemapper is one of many old project that the OKF tech team is currently assessing the maintenance of. Can I ask you how often you use it?

Also, @rufuspollock do you have any interest/time to look into restoring functionality in the mean time?

**Comment by kcirsresearch** [comment]
> 
> 
> Hi @kcirsresearch! Timemapper is one of many old project that the OKF tech team is currently assessing the maintenance of. Can I ask you how often you use it?
> 
> Also, @rufuspollock do you have any interest/time to look into restoring functionality in the mean time?

Hi @lwinfree ! Thanks for your response!

I use it frequently - I'm part of a team developing educational resources for English and literature classes, and have been using TimeMapper over the past year with the hopes of having a resource that could continue to be available in the future for students, teachers, and other users! It's also something I've recommended to others, and would be very happy to see maintained.

**Comment by amercader** [comment]
Thanks all for providing feedback on TimeMapper usage. We'd love to keep this online and used by people but at the same time the changes needed to fix it are not trivial, the codebase is ancient and our resources are limited.


Technically this is indeed caused by changes in the Google Sheets API used under the hood. 

* v3 is deprecated and[ v4 should be used](https://cloud.google.com/blog/products/g-suite/migrate-your-apps-use-latest-sheets-api). eg this call fired up [here](https://github.com/okfn/timemapper/blob/065085aa1a8b3eb066d8909e2977252548f3e42e/public/js/create.js#L96) should use a different URL. The JSON object returned is different, so the logic needs to be updated ([ref](https://developers.google.com/sheets/api/guides/migration#v4-api_5)):

```
# v3
https://spreadsheets.google.com/feeds/worksheets/<SPREADSHEET_ID>/public/basic?alt=json
# v4 
https://sheets.googleapis.com/v4/spreadsheets/<SPREADSHEET_ID>?key=<API_KEY>
```
   
* v4 requires an [API key](https://developers.google.com/sheets/api/guides/authorizing) on any request. This needs to be stored somewhere and we probably need to handle quotas etc If API keys are not enough we need to implement Oauth authentication
* I haven't tracked any further requests down the line but I imagine that there is at least another one to get the actual data from the spreadsheet.

This should address this specific issue but looking ahead the project needs a good update, with several of each requirements outdated. Different parts of the application are broken like the "Pick from Google Drive", etc

I'll get one of our devs to try to apply a quick fix to at least getting it back to a usable state. If that proves unsuccessful we'll need to put the project on hold until we can secure more funding/resources and if that doesn't happen I'm afraid we'll have to sunset the project.

@rufuspollock let me know if you or someone at Datopian could help with trying to fix this specific Google APIs issue

**Comment by kcirsresearch** [comment]
@amercader Thanks for your input and transparency! I'm hoping the fixes can be made, but I understand if it isn't feasible given your resources.

If any updates are to happen, a change I would love to see would be for the time map to read its data from something stable like an uploaded spreadsheet file, rather than a shared link from a source susceptible to updates. 

However, that's purely in the realm of speculation based my personal convenience - I have no idea the difficulty or resources involved in coding such a thing.  Thanks again for your help!

**Comment by rufuspollock** [comment]
@amercader this is something that it is possible to help sort out (i'd mentioned this ~1.5y ago actually to Jo). Would you be open then to @datopian taking this on (and ultimately transitioning the domain)?

**Comment by asegal20902** [comment]
@amercader @rufuspollock I would very much appreciate enabling TimeMapper to survive, as I have found it useful in my digital curation projects, especially creating TimeMaps of Camilo Jose Vergara's photographs of American cities over time.

**Comment by thtbln** [comment]
I've been just able to create a new timemap by copying the "key" part from the Google Drive link and using the link: https://docs.google.com/spreadsheet/ccc?key=1UsrVT5_B0gL43CduZEyXevGHK1bo7kEp8J7BNPOXMY4#gid=0 
However, the new timemap doesn't show up as well as the older ones in my account (http://timemapper.okfnlabs.org/thtbln).

**Comment by asegal20902** [comment]
Hi @thtbln I could not see the Hawaii/Germany map come up at http://timemapper.okfnlabs.org/thtbln/hawaii-germany. The link that you have is to the spreadsheet. What link should I use? 
BTW I am digitizing maps of Hawaii at the Library of Congress

**Comment by amercader** [comment]
Here's an update on the current situation:

* After some heroic efforts @aivuk has been able to update the ancient Timemapper codebase to allow spreadsheets to be parsed again (with some caveats, see below)
* Some existing timelines stored on users profiles are still not being loaded, @aivuk is on this and will hopefully get it fixed soon.
* We don't know if everything is working as before! Let us know if there is something off adding a comment to this issue
* It's pretty clear that the current code base is not fit for purpose. In the coming days we will post an implementation plan for a new Timemapper version. The goal is that all current timelines and URLs remain unaffected.

Thanks everyone for bearing with us

**Comment by aivuk** [comment]
> Some existing timelines stored on users profiles are still not being loaded, @aivuk is on this and will hopefully get it fixed soon.

All the examples in the frontpage are working again and most of the old user timemaps must be working also.

**Comment by alanger06** [comment]
Thank you so much for working on this.  Is there anything special we need to do to update our existing source sheets to get them to load? I have one of those user maps that's still hanging on the load screen. 

http://timemapper.okfnlabs.org/artiflection/immigration-and-world-history-timeline

**Comment by alanger06** [comment]
Thank you!

**Comment by amercader** [comment]
To all affected by this issue, we are planning on building a new version of Timemapper (keeping all existing data and functionality) over the next months. Progress can be tracked here: https://github.com/okfn/timemapper/issues/229
